language: python

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"

before_install:
    - sudo apt-get -qq update
    - sudo mkdir -p /builds
    - sudo chmod a+rw /builds

install:
    - pip3 install flake8 -r requirements.txt
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - sudo env "PATH=$PATH" make clean
    - make all
    - sudo env "PATH=$PATH" make install

script: nosetests
